### ISSUE TITLE
Is it compatible with windows？

### ISSUE THREAD

**Issue by sylvoslee** [adamcharnock/lightbus#22]

**Comment by adamcharnock** [comment]
Hi @sylvoslee. I must confess I haven't tested it on Windows, but I don't think there should be much of a compatibility issue. If you try please let me know how you get on!

**Comment by sylvoslee** [comment]
Python ImportError: No module named resource
The resource module is not not compatible on windows

**Comment by adamcharnock** [comment]
Ok, thanks for giving it a go @sylvoslee! I've created an issue for this in #23. This isn't going to be something I can sort out myself. If you or anyone else wants to take a look at this I would definitely welcome it.
